
package test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.5-hudson-$BUILD_NUMBER-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SecureWebService", targetNamespace = "http://test/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SecureWebService {


    /**
     * 
     * @param arg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://test/", className = "test.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://test/", className = "test.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg", targetNamespace = "")
        String arg);

    /**
     * 
     * @param arg
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayBye", targetNamespace = "http://test/", className = "test.SayBye")
    @ResponseWrapper(localName = "sayByeResponse", targetNamespace = "http://test/", className = "test.SayByeResponse")
    public String sayBye(
        @WebParam(name = "arg", targetNamespace = "")
        String arg);

}
